# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c46ee2d6eef9b01b37dfcb250eb6425b14106d34836d69409e29ea5296cbf816b407886bd09f074a507a17b8e271707d8cacd5a4f700c8938264734b6c7734a

test:
  secret_key_base: 95f38b3092123adbd6453328ffa164b94dd752c93e02621bee36988fbd222c3d909045e54128c89c1d30102a914486724d9b2dafa97bef43796250b3d097e54b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
